project_id = "gblpsayemvvgtjtcfgdn"

[functions.ai-generate-questions]
verify_jwt = false

[functions.notify-new-response]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.analyze-chat]
verify_jwt = false
